---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

component_skel:
  manila_api:
    belongs_to:
      - manila_all
  manila_scheduler:
    belongs_to:
      - manila_all
  manila_share:
    belongs_to:
      - manila_all
  manila_data:
    belongs_to:
      - manila_all


container_skel:
  manila_api_container:
    belongs_to:
      - manila-infra_containers
    contains:
      - manila_api
      - manila_scheduler
  manila_shares_container:
    belongs_to:
      - manila_containers
    contains:
      - manila_share
      - manila_data
    properties:
# When using LVM or any iSCSI based (see LP#1226855) manila backends, such as
# NetApp with iSCSI protocol, it is advised to run manila-shares on metal.
# If you are using a different backend you may want to remove "is_metal: true".
# Otherwise if manila-shares is already running in containers you may want to
# leave is_metal off, alternatively you will have to migrate your shares once
# deployed on metal.
      is_metal: true


physical_skel:
  manila-infra_containers:
    belongs_to:
      - all_containers
  manila-infra_hosts:
    belongs_to:
      - hosts
  manila_containers:
    belongs_to:
      - all_containers
  manila_hosts:
    belongs_to:
      - hosts
